### ISSUE TITLE
[BUG] Anti-X-Ray

### ISSUE THREAD

**Issue by MelodyMcKenna** [GorilloCraft/Server#135]
**Describe the bug**
The anti-x-ray on our SMP doesn't appear to be working.

**To Reproduce**
1. Turn on x-ray
2. Mine shiny blue rocks

**Expected behavior**
Anti-x-ray prevents any x-ray mods/resource packs from accurately locating ores.

**Screenshots**
See video in #s2-Bug-Reporting

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
So, I just took a look at the configuration file:

```
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2
    hidden-blocks:
```

The anti xray system is enabled...but yesterday, I did change a setting for those with the permission which allows them to bypass the antixray, so I think that is why you are able to bypass it.
