### ISSUE TITLE
[BUG] Daily Challenge Cowboy In Training only requires 1 horse 

### ISSUE THREAD

**Issue by HagridHills** [GorilloCraft/Server#138]
**Describe the bug**
it say to complete the quest, you must ride a wild horse 2 times. but it only requires to ride it once 

**To Reproduce**
1. have the Cowboy In Training daily challenge
2. find a wild horse
3. tame it and put a saddle on it
4. then ride it 1 or 2 blocks and itl say its completed 

**Expected behavior**
you have to tame 2 horses and ride them 

**Screenshots**
![image](https://user-images.githubusercontent.com/42377455/188311471-a26fccdb-670b-4251-a38e-18e9a2077f1a.png)

**Server that is affected (Global, Hub, Survival, Creative)**
Survival

**Comment by ImSnipper** [comment]
```
  4:
    type: ride-mob
    variable: horse
    name: 'Daily - Cowboy in Training'
    required-progress: 2
    points: 50
    item:
      material: saddle
      name: '&b&lCHALLENGE: &fCowboy in Training'
      lore:
        - '&fTo complete this quest, you must'
        - '&fride a wild horse 2 times.'
        - ''
        - '&bInformation'
        - '&fPoints: &a50x'
        - '&fProgress: &a%total_progress%&8/&c%required_progress%'
```

Oddly enough, the required progress is set to 2. Not sure why this is happening. Will look into it...
